//// <auto-generated />
////
//// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
////
////    using ElevenMovie.Models;
////
////    var welcome = Welcome.FromJson(jsonString);

//namespace ElevenMovie.Models
//{
//    using System;
//    using System.Collections.Generic;

//    using System.Globalization;
//    using Newtonsoft.Json;
//    using Newtonsoft.Json.Converters;

//    public partial class MovieSearchResults
//    {
//        [JsonProperty("page")]
//        public long Page { get; set; }

//        [JsonProperty("results")]
//        public Result[] Results { get; set; }

//        [JsonProperty("total_pages")]
//        public long TotalPages { get; set; }

//        [JsonProperty("total_results")]
//        public long TotalResults { get; set; }
//    }

//    public partial class Result
//    {
//        [JsonProperty("adult")]
//        public bool Adult { get; set; }

//        [JsonProperty("backdrop_path")]
//        public string BackdropPath { get; set; }

//        [JsonProperty("genre_ids")]
//        public long[] GenreIds { get; set; }

//        [JsonProperty("id")]
//        public long Id { get; set; }

//        [JsonProperty("original_language")]
//        public string OriginalLanguage { get; set; }

//        [JsonProperty("original_title")]
//        public string OriginalTitle { get; set; }

//        [JsonProperty("overview")]
//        public string Overview { get; set; }

//        [JsonProperty("popularity")]
//        public double Popularity { get; set; }

//        [JsonProperty("poster_path")]
//        public string PosterPath { get; set; }

//        [JsonProperty("release_date")]
//        public DateTimeOffset ReleaseDate { get; set; }

//        [JsonProperty("title")]
//        public string Title { get; set; }

//        [JsonProperty("video")]
//        public bool Video { get; set; }

//        [JsonProperty("vote_average")]
//        public double VoteAverage { get; set; }

//        [JsonProperty("vote_count")]
//        public long VoteCount { get; set; }
//    }

//    public partial class MovieSearchResults
//    {
//        public static MovieSearchResults FromJson(string json) => JsonConvert.DeserializeObject<MovieSearchResults>(json, ElevenMovie.Models.Converter.Settings);
//    }

//    public static class Serialize
//    {
//        public static string ToJson(this MovieSearchResults self) => JsonConvert.SerializeObject(self, ElevenMovie.Models.Converter.Settings);
//    }

//    internal static class Converter
//    {
//        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
//        {
//            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
//            DateParseHandling = DateParseHandling.None,
//            Converters =
//            {
//                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
//            },
//        };
//    }
//}
